sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t lubabalobuwa64/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lubabalobuwa64/react-test npm test

after_success:
  - docker build -t lubabalobuwa64/multi-client ./client
  - docker build -t lubabalobuwa64/multi-nginx ./nginx
  - docker build -t lubabalobuwa64/multi-server ./server
  - docker build -t lubabalobuwa64/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push lubabalobuwa64/multi-client
  - docker push lubabalobuwa64/multi-nginx
  - docker push lubabalobuwa64/multi-server
  - docker push lubabalobuwa64/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-047690742143
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY